<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>organization_tab_all_icons</name>
   <tag></tag>
   <elementGuidId>6cf55709-5551-4bbb-aa0f-ae8791c9b1a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='switcherTabs-pane-2']/ul/li/div/div[1]/div[1]/*[name()='svg']/*[name()='path']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
