<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>swictherlogo</name>
   <tag></tag>
   <elementGuidId>34a8d643-2544-4137-a5e8-2dd74912f835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='init']/div/div[4]/div/div[2]/div/span/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://dqfn4clx0bazt.cloudfront.net/init/f6f2f4d5e61806aa6e5724489a09bc3e.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__gsmLogo___2sD5e</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;init&quot;)/div[@class=&quot;style__appPanelContainer___1EvkK&quot;]/div[@class=&quot;style__SwitchPanelContent___2_M2e col-lg-2 col-md-2 col-sm-2 col-xs-3&quot;]/div[@class=&quot;style__switchShape___m7QrI&quot;]/div[@class=&quot;style__BackgroundStyled___1BCYv&quot;]/div[@class=&quot;style__sidebar___T6MD6&quot;]/span[1]/div[@class=&quot;style__logoContainer___3nWvY row&quot;]/div[@class=&quot;col-lg-10 col-md-10 col-sm-10 col-xs-10&quot;]/img[@class=&quot;style__gsmLogo___2sD5e&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='init']/div/div[4]/div/div[2]/div/span/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://dqfn4clx0bazt.cloudfront.net/init/f6f2f4d5e61806aa6e5724489a09bc3e.svg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
