<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_Valid and Invalid</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>230</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>799a4984-160f-4f97-8513-c973e8d5b44e</testSuiteGuid>
   <testCaseLink>
      <guid>a301abda-0e93-43d3-94de-ea34100dae7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Atlas Platform/Platform Navigation/Login/Default Logins/TC_100_ForSecurityURLSAcceptance</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8aa90486-5253-4057-ac00-47994c5742fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Atlas Platform/Platform Navigation/Login/InValid Pasword_Login</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>3de4702d-a6a4-4809-8c9f-802158e776b1</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>43-57</value>
         </iterationEntity>
         <testDataId>Data Files/AMP_Y</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>3de4702d-a6a4-4809-8c9f-802158e776b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>87a1705d-bfaa-4414-a832-e4d39b0964e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3de4702d-a6a4-4809-8c9f-802158e776b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>6f7b3bb8-9f36-49d3-b444-29f2b74f9fcd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04ee0d63-a2ea-45af-971b-bddf7846664c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Atlas Platform/Platform Navigation/Login/InValid Email ID_Login</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>bf8bdddd-7cab-4c1e-bd4b-53e566a935e4</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>22-41</value>
         </iterationEntity>
         <testDataId>Data Files/AMP_Y</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>bf8bdddd-7cab-4c1e-bd4b-53e566a935e4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>0e64ab1a-2e7e-4fb8-a0c1-445e91930d90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bf8bdddd-7cab-4c1e-bd4b-53e566a935e4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>da2d6be7-b1e3-480a-b78b-ff4ddf997f96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>668d59fd-6aa8-4c0b-8237-12d2d8a4d7f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Atlas Platform/Platform Navigation/Login/LG-01_Validate_Login_Feature_with_Valid_Credentials</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bfd1b5e3-9fc8-4487-9684-e1261aac0c95</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-19</value>
         </iterationEntity>
         <testDataId>Data Files/AMP_Y</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>bfd1b5e3-9fc8-4487-9684-e1261aac0c95</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>7ee908a4-48bf-4a84-94aa-40bcc8d3a93d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bfd1b5e3-9fc8-4487-9684-e1261aac0c95</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>5c3d6ca3-f53c-4e7d-b534-bf68eac1026d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>213242b4-5603-4641-9f49-12b3085522f9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
